name: Build

on:
  workflow_call:
    inputs:
      version:
        description: "Version string to embed in the build"
        type: string
        required: true

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            container: cachyos/cachyos-v3:latest
          - os: windows-latest

    runs-on: ${{ matrix.os }}
    container: ${{ matrix.container }}

    steps:
      - uses: actions/checkout@main

      - name: Setup xmake
        uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: latest
          package-cache: true
          package-cache-key: ${{ runner.os }}-xmake-packages

      - name: Install Dependencies (Linux)
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: |
          sudo pacman -Syu --noconfirm git gcc

      - name: Build with xmake
        run: |
          xmake f -p ${{ matrix.os == 'windows-latest' && 'windows' || 'linux' }} -m release --version=${{ inputs.version }} -y
          xmake -vvvD -y

      - name: Rename build output
        shell: bash
        run: |
          if [ "${{ matrix.os }}" == "windows-latest" ]; then
            mv build/multi-frp.exe build/multi-frp-windows-amd64-${{ inputs.version }}.exe
          else
            mv build/multi-frp build/multi-frp-linux-amd64-${{ inputs.version }}
          fi

      - name: Upload build artifacts
        uses: actions/upload-artifact@main
        with:
          name: build-${{ matrix.os }}
          path: build/multi-frp*
