name: Build

on:
  workflow_call:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@main

      - name: Setup xmake
        uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: latest
          package-cache: true
          package-cache-key: ${{ runner.os }}-xmake-packages

      - name: Install UPX (for Windows builds)
        if: ${{ matrix.os == 'windows-latest' }}
        uses: MinoruSekine/setup-scoop@v4.0.2
        with:
          buckets: extras
          apps: upx

      - name: Build with xmake
        run: |
          xmake f -p ${{ matrix.os == 'windows-latest' && 'windows' || 'linux' }} -m release -y
          xmake -vvvD -y
      
      - name: Rename build output
        shell: bash
        run: |
          if [ "${{ matrix.os }}" == "windows-latest" ]; then
            mv build/multi-frp.exe build/multi-frp-windows-amd64.exe
          else
            mv build/multi-frp build/multi-frp-linux-amd64
          fi

      - name: Upload build artifacts
        uses: actions/upload-artifact@main
        with:
          name: build-${{ matrix.os }}
          path: build/multi-frp*
